import { randomBytes } from 'crypto';
import type { ApplyForm, FormQuestion } from '@linkedin-job-applier/shared';
import type { LinkedInGraphQLResponse, LinkedInIncludedItem } from '../../types/linkedin';

/**
 * Parses the raw LinkedIn Voyager GraphQL response for an Easy Apply form
 * into a structured ApplyForm object.
 */
export function parseApplyForm(jsonData: LinkedInGraphQLResponse): ApplyForm {
  const included = jsonData.included ?? [];

  // ── Build a map of form elements by URN ────────────────────────────────────
  const formElementsMap = new Map<string, LinkedInIncludedItem>();
  for (const item of included) {
    if (
      item.$type ===
        'com.linkedin.voyager.dash.common.forms.FormElement' ||
      item.$type ===
        'com.linkedin.voyager.dash.jobs.JobApplicationFileUploadFormElement'
    ) {
      const urn = item.formElementUrn ?? item.urn;
      if (urn) formElementsMap.set(urn, item);
    }
  }

  // ── referenceId: generated by client, not from server ─────────────────────
  // The LinkedIn API accepts any random base64(16 bytes) as referenceId.
  // It is NOT returned in the GET apply-form response — it's a client-generated
  // tracking token that must be created fresh for each submission attempt.
  const referenceId: string = 'NotAvailable';

  // ── Collect available resume URNs ──────────────────────────────────────────
  // These come from `com.linkedin.voyager.dash.jobs.Resume` items in `included`.
  // The most-recently-used one (sorted by lastUsedAt desc) should be used.
  const resumeItems = included
    .filter((item) => item.$type === 'com.linkedin.voyager.dash.jobs.Resume')
    .sort((a, b) => {
      const aTime = typeof a.lastUsedAt === 'number' ? a.lastUsedAt : 0;
      const bTime = typeof b.lastUsedAt === 'number' ? b.lastUsedAt : 0;
      return bTime - aTime;
    });
  const resumeUrns: string[] = resumeItems
    .map((r) => r.entityUrn as string | undefined)
    .filter((u): u is string => typeof u === 'string');

  // ── Extract resumeUploadFormElementUrn + resumeUrns from OnsiteApplyApplication ──
  // Real path: jobApplicationForms[].questionGroupings[].customizedFormSection.fileUploadFormSection
  // The usedResumesResolutionResults on the RESUME grouping also gives us resume URNs.
  let resumeUploadFormElementUrn: string | undefined;
  const onsiteApp = included.find(
    (item) => item.$type === 'com.linkedin.voyager.dash.jobs.OnsiteApplyApplication',
  );
  if (onsiteApp) {
    const forms = (onsiteApp.jobApplicationForms as Array<Record<string, unknown>> | undefined) ?? [];
    outer: for (const form of forms) {
      const groupings = (form['questionGroupings'] as Array<Record<string, unknown>> | undefined) ?? [];
      for (const g of groupings) {
        // Path 1: customizedFormSection.fileUploadFormSection (confirmed by inspection)
        const custom = g['customizedFormSection'] as Record<string, unknown> | null | undefined;
        const fileSection = (custom?.['fileUploadFormSection'] ??
          g['fileUploadFormSection']) as Record<string, unknown> | null | undefined;
        if (fileSection) {
          const el = fileSection['fileUploadFormElement'] as Record<string, unknown> | undefined;
          if (el) {
            resumeUploadFormElementUrn = (el['formElementUrn'] ?? el['urn']) as string | undefined;
            // Also collect usedResumes from this RESUME grouping as primary source
            const usedResumes = (g['usedResumesResolutionResults'] as string[] | undefined) ?? [];
            if (usedResumes.length > 0 && resumeUrns.length === 0) {
              resumeUrns.push(...usedResumes);
            }
            if (resumeUploadFormElementUrn) break outer;
          }
        }
      }
    }
  }

  // ── Sections ───────────────────────────────────────────────────────────────
  interface ParsedStep {
    title: string;
    questions: FormQuestion[];
  }

  const steps: ParsedStep[] = [];

  const sections = included.filter(
    (item) =>
      item.$type ===
      'com.linkedin.voyager.dash.jobs.JobApplicationFormSection',
  );

  for (const section of sections) {
    const stepQuestions: FormQuestion[] = [];
    let title = 'Seção';

    if (
      section.questionGroupingType === 'RESUME' ||
      section.questionGroupingType === 'COVER_LETTER'
    ) {
      title =
        section.customizedFormSection?.fileUploadFormSection?.title ??
        section.questionGroupingType;
      const element = section.customizedFormSection?.fileUploadFormSection
        ?.fileUploadFormElement as LinkedInIncludedItem | undefined;
      if (element) {
        stepQuestions.push(parseField(element));
      }
    } else if (section.formSection) {
      title =
        section.formSection.title?.text ?? 'Informações Adicionais';
      const groups = section.formSection.formElementGroups ?? [];
      for (const group of groups) {
        for (const urn of group['*formElements'] ?? []) {
          const el = formElementsMap.get(urn);
          if (el) stepQuestions.push(parseField(el));
        }
      }
    }

    if (stepQuestions.length > 0) {
      steps.push({
        title,
        questions: stepQuestions.filter(
          (q) => q.title && q.title !== 'Unknown Question',
        ),
      });
    }
  }

  // ── Fallback: list all elements if section parsing yielded nothing ─────────
  if (steps.length === 0) {
    const flatQuestions = Array.from(formElementsMap.values())
      .map(parseField)
      .filter((q) => q.title && q.title !== 'Unknown Question');
    if (flatQuestions.length > 0) {
      steps.push({ title: 'Formulário de Candidatura', questions: flatQuestions });
    }
  }

  const validSteps = steps.filter((s) => s.questions.length > 0);

  return {
    success: true,
    steps: validSteps,
    questions: validSteps.flatMap((s) => s.questions),
    referenceId,
    resumeUploadFormElementUrn,
    resumeUrns,
  };
}

// ─── Private helper ───────────────────────────────────────────────────────────

function parseField(el: LinkedInIncludedItem): FormQuestion {
  // File upload elements are their own $type
  if (
    el.$type ===
    'com.linkedin.voyager.dash.jobs.JobApplicationFileUploadFormElement'
  ) {
    return {
      urn: el.formElementUrn ?? el.urn ?? '',
      required: Boolean(el.required),
      title:
        (typeof el.title === 'string' ? el.title : el.title?.text) ??
        el.uploadFileCtaText ??
        'Upload File',
      type: 'file',
      options: el.mimeTypes ?? [],
    };
  }

  let type = 'unknown';
  let options: string[] = [];
  let optionUrns: string[] = [];
  let optionEnumStrings: string[] = [];

  const component = el.formComponentResolutionResult;
  if (component?.singleLineTextFormComponent) type = 'text';
  if (component?.multilineTextFormComponent) type = 'multiline-text';
  if (component?.checkboxFormComponent) {
    type = 'checkbox';
    options =
      component.checkboxFormComponent.textSelectableOptions
        ?.map((o: Record<string, unknown>) => (o.optionText as Record<string, string>)?.text)
        .filter((t: unknown): t is string => typeof t === 'string') ?? [];
  }
  if (component?.textEntityListFormComponent) {
    type = 'dropdown';
    const selectableOptions = component.textEntityListFormComponent.textSelectableOptions ?? [];
    options = selectableOptions
      .map((o: Record<string, unknown>) => (o.optionText as Record<string, string>)?.text)
      .filter((t: unknown): t is string => typeof t === 'string');
    optionUrns = selectableOptions
      .map((o: Record<string, unknown>) => {
        const opt = o.option as Record<string, unknown> | undefined;
        const urn = (opt?.optionUrn || o.entityUrn) as string | undefined;
        return urn && urn.startsWith('urn:') ? urn : undefined;
      })
      .filter((u: unknown): u is string => typeof u === 'string');
    // Extract enum strings for options that have no URN (e.g. Yes/No multipleChoice)
    optionEnumStrings = selectableOptions
      .map((o: Record<string, unknown>) => {
        const opt = o.option as Record<string, unknown> | undefined;
        return (opt?.optionEnumString ?? null) as string | null;
      })
      .filter((e): e is string => typeof e === 'string' && e.length > 0);
  }
  if (component?.singleTypeaheadEntityFormComponent) type = 'typeahead';
  if (component?.dateRangeFormComponent) type = 'date-range';
  if (component?.phoneNumberFormComponent) type = 'phone';
  if (component?.numericFormComponent) type = 'numeric';

  const fallbackTitle =
    component?.textEntityListFormComponent?.placeHolderText?.text ??
    'Unknown Question';
  const questionTitle =
    (typeof el.title === 'object' ? el.title?.text : el.title) ??
    fallbackTitle;

  return {
    urn: el.urn ?? '',
    required: Boolean(el.required),
    title: questionTitle,
    type,
    options,
    ...(optionUrns.length > 0 ? { optionUrns } : {}),
    ...(optionEnumStrings.length > 0 ? { optionEnumStrings } : {}),
  };
}
