import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

// Simple translation map for common API documentation terms
const translations: Record<string, string> = {
  // Headers
  'title': 'title',
  'description': 'description',

  // Common terms
  'Overview': 'Visão Geral',
  'Request': 'Requisição',
  'Response': 'Resposta',
  'Parameters': 'Parâmetros',
  'Body': 'Corpo',
  'Headers': 'Cabeçalhos',
  'Query': 'Consulta',
  'Path': 'Caminho',
  'Required': 'Obrigatório',
  'Optional': 'Opcional',
  'Example': 'Exemplo',
  'Success': 'Sucesso',
  'Error': 'Erro',
  'Authentication': 'Autenticação',
  'Authorization': 'Autorização',

  // HTTP methods
  'GET': 'GET',
  'POST': 'POST',
  'PUT': 'PUT',
  'DELETE': 'DELETE',
  'PATCH': 'PATCH',

  // Data types
  'string': 'string',
  'number': 'número',
  'boolean': 'booleano',
  'object': 'objeto',
  'array': 'array',

  // Common phrases
  'This endpoint': 'Este endpoint',
  'Returns': 'Retorna',
  'The request body must contain': 'O corpo da requisição deve conter',
  'was generated by': 'foi gerado por',
  'Do not edit this file directly': 'Não edite este arquivo diretamente',
};

function translateContent(content: string): string {
  let translated = content;

  // Translate generated comment
  translated = translated.replace(
    /This file was generated by Fumadocs\. Do not edit this file directly\./g,
    'Este arquivo foi gerado pelo Fumadocs. Não edite este arquivo diretamente.'
  );

  // Update openapi file references to point to the Portuguese versions
  translated = translated.replace(/openapi-backend\.json/g, 'openapi-backend-pt-BR.json');
  translated = translated.replace(/openapi-publisher\.json/g, 'openapi-publisher-pt-BR.json');
  translated = translated.replace(/openapi\.json/g, 'openapi-pt-BR.json');

  return translated;
}

function copyAndTranslateFile(srcPath: string, destPath: string) {
  const content = readFileSync(srcPath, 'utf-8');
  const translated = translateContent(content);

  // Ensure destination directory exists
  const destDir = path.dirname(destPath);
  if (!existsSync(destDir)) {
    mkdirSync(destDir, { recursive: true });
  }

  writeFileSync(destPath, translated, 'utf-8');
  console.log(`Translated: ${path.relative(projectRoot, destPath)}`);
}

function copyDirectoryRecursive(srcDir: string, destDir: string) {
  if (!existsSync(srcDir)) {
    return;
  }

  const items = readdirSync(srcDir);

  for (const item of items) {
    const srcPath = path.join(srcDir, item);
    const destPath = path.join(destDir, item);

    const stat = statSync(srcPath);

    if (stat.isDirectory()) {
      copyDirectoryRecursive(srcPath, destPath);
    } else if (item.endsWith('.mdx') || item.endsWith('.json')) {
      // Skip if file already exists in destination
      if (!existsSync(destPath)) {
        copyAndTranslateFile(srcPath, destPath);
      } else {
        console.log(`Skipped (already exists): ${path.relative(projectRoot, destPath)}`);
      }
    }
  }
}

async function main() {
  const enDir = path.join(projectRoot, 'content/docs/en');
  const ptBRDir = path.join(projectRoot, 'content/docs/pt-BR');

  console.log('Starting translation from en/ to pt-BR/...\n');

  // Copy and translate all subdirectories
  const subdirs = ['gateway', 'job-backend', 'publisher-backend'];

  for (const subdir of subdirs) {
    const srcPath = path.join(enDir, subdir);
    const destPath = path.join(ptBRDir, subdir);

    console.log(`\nProcessing ${subdir}/...`);
    copyDirectoryRecursive(srcPath, destPath);
  }

  console.log('\n✅ Translation complete!');
}

main().catch((err) => {
  console.error('Translation failed:', err);
  process.exit(1);
});
